openapi: 3.0.0
info:
  title: (title)
  version: 0.0.0
tags: []
paths: {}
components:
  schemas:
    AvailabilityStatus:
      type: string
      enum:
        - AVAILABLE
        - FREESALE
        - SOLD_OUT
        - LIMITED
        - CLOSED
      example: AVAILABLE
    AvailabilityType:
      type: string
      enum:
        - START_TIME
        - OPENING_HOURS
      example: START_TIME
    BookingStatus:
      type: string
      enum:
        - ON_HOLD
        - CONFIRMED
        - EXPIRED
        - CANCELLED
        - REDEEMED
        - PENDING
        - REJECTED
      example: CONFIRMED
    CancellationCutoffUnit:
      type: string
      enum:
        - hour
        - minute
        - day
      example: hour
    Capability:
      type: string
      enum:
        - octo/adjustments
        - octo/cart
        - octo/content
        - octo/mappings
        - octo/packages
        - octo/pickups
        - octo/pricing
        - octo/questions
    CategoryLabel:
      type: string
      enum:
        - multi-day
        - city-cards
        - adults-only
        - animals
        - audio-guide
        - beaches
        - bike-tours
        - boat-tours
        - classes
        - day-trips
        - family-friendly
        - fast-track
        - food
        - guided-tours
        - history
        - hop-on-hop-off
        - literature
        - live-music
        - museums
        - nightlife
        - outdoors
        - private-tours
        - romantic
        - recurring-events
        - self-guided
        - small-group-tours
        - sports
        - theme-parks
        - walking-tours
        - wheelchair-accessible
        - accommodation-included
        - trip-difficulty-easy
        - trip-difficulty-medium
        - trip-difficulty-hard
      example: adults-only
    CommentaryFormat:
      type: string
      enum:
        - IN_PERSON
        - RECORDED_AUDIO
        - WRITTEN
        - OTHER
      example: IN_PERSON
    ContactField:
      type: string
      enum:
        - firstName
        - lastName
        - emailAddress
        - phoneNumber
        - country
        - notes
        - locales
        - allowMarketing
        - postalCode
      example: emailAddress
    DeliveryFormat:
      type: string
      enum:
        - PDF_URL
        - QRCODE
        - CODE128
        - PKPASS_URL
      example: QRCODE
    DeliveryMethod:
      type: string
      enum:
        - VOUCHER
        - TICKET
      example: TICKET
    DeliveryOption:
      type: object
      required:
        - deliveryFormat
        - deliveryValue
      properties:
        deliveryFormat:
          allOf:
            - $ref: '#/components/schemas/DeliveryFormat'
          description: |-
            The format in which vouchers for this product are delivered. Each format specifies how the vouchers will be represented:
            QRCODE: A code presented as a QR Code, commonly used for scanning at entry points.
            CODE128: A linear barcode format widely used for retail and ticketing purposes.
            AZTECCODE: A two-dimensional barcode format similar to QR codes but more compact. It is optimized for small spaces and often used in transportation and event ticketing.
            PDF_URL: A URL linking to a downloadable PDF containing the complete ticket details for this product.
            PKPASS_URL: A URL for adding the ticket to Apple Wallet (Passbook) for easy access on iOS devices.
            This field ensures resellers can understand and integrate the appropriate ticket delivery formats specifically associated with this product."
          example: QRCODE
        deliveryValue:
          type: string
          description: The string with the value of the delivery option, e.g. value behind the QRCODE, CODE128, AZTECCODE, or URL hosting the file for PDF_URL or PKPASS_URL)
          example: ''
      example:
        deliveryFormat: QRCODE
        deliveryValue: ''
    DurationUnit:
      type: string
      enum:
        - minute
        - hour
        - day
      example: hour
    FeatureType:
      type: string
      enum:
        - INCLUSION
        - EXCLUSION
        - HIGHLIGHT
        - PREBOOKING_INFORMATION
        - PREARRIVAL_INFORMATION
        - REDEMPTION_INSTRUCTION
        - ACCESSIBILITY_INFORMATION
        - ADDITIONAL_INFORMATION
        - BOOKING_TERM
        - CANCELLATION_TERM
      example: CANCELLATION_TERM
    LocationType:
      type: string
      enum:
        - START
        - ITINERARY_ITEM
        - POINT_OF_INTEREST
        - ADMISSION_INCLUDED
        - END
        - REDEMPTION
      example: POINT_OF_INTEREST
    MediaRel:
      type: string
      enum:
        - LOGO
        - COVER
        - GALLERY
      example: LOGO
    MediaType:
      type: string
      enum:
        - image/jpeg
        - image/png
        - video/mp4
        - video/avi
        - external/youtube
        - external/vimeo
      example: image/jpeg
    OpeningHours:
      type: object
      required:
        - from
        - to
      properties:
        from:
          type: string
          description: The opening time
          example: '08:00'
        to:
          type: string
          description: The closing time
          example: '16:00'
      description: Defines the opening hours for this availability, even for start time-based availability. Supports multiple periods for breaks in the day.
      example:
        from: '08:00'
        to: '16:00'
    PricingPer:
      type: string
      enum:
        - BOOKING
        - UNIT
      example: BOOKING
    RedemptionMethod:
      type: string
      enum:
        - DIGITAL
        - PRINT
        - MANIFEST
      example: DIGITAL
    Refund:
      type: string
      enum:
        - FULL
        - PARTIAL
        - NONE
      example: PARTIAL
    Ticket:
      type: object
      required:
        - redemptionMethod
        - utcRedeemedAt
        - deliveryOptions
      properties:
        redemptionMethod:
          allOf:
            - $ref: '#/components/schemas/RedemptionMethod'
          description: |-
            Specifies how the voucher can be redeemed by the customer:
            DIGITAL: The voucher must be presented, either scanned from a digital device (e.g., smartphone) or as a printed copy. Redemption requires a valid voucher or ticket, even in digital form.
            MANIFEST: The customer’s name, reference, or other information is checked against a manifest by the supplier. Redemption does not require a ticket or voucher.
            PRINT: A physical printed voucher is strictly required for redemption and must be presented at the time of use.
            This field ensures resellers and customers understand the specific requirements for redeeming this booking.
          example: DIGITAL
        utcRedeemedAt:
          type: string
          nullable: true
          description: |-
            Specifies how the voucher can be redeemed by the customer:
            DIGITAL: The voucher must be presented, either scanned from a digital device (e.g., smartphone) or as a printed copy. Redemption requires a valid voucher or ticket, even in digital form.
            MANIFEST: The customer’s name, reference, or other information is checked against a manifest by the supplier. Redemption does not require a ticket or voucher.
            PRINT: A physical printed voucher is strictly required for redemption and must be presented at the time of use.
            This field ensures resellers and customers understand the specific requirements for redeeming this booking.
          example: '2021-10-27T23:28:43Z'
        deliveryOptions:
          type: array
          items:
            $ref: '#/components/schemas/DeliveryOption'
          description: |-
            Specifies how the voucher can be redeemed by the customer:
            DIGITAL: The voucher must be presented, either scanned from a digital device (e.g., smartphone) or as a printed copy. Redemption requires a valid voucher or ticket, even in digital form.
            MANIFEST: The customer’s name, reference, or other information is checked against a manifest by the supplier. Redemption does not require a ticket or voucher.
            PRINT: A physical printed voucher is strictly required for redemption and must be presented at the time of use.
            This field ensures resellers and customers understand the specific requirements for redeeming this booking.
          example:
            - deliveryFormat: QRCODE
              deliveryValue: ''
      example:
        redemptionMethod: DIGITAL
        utcRedeemedAt: '2021-10-27T23:28:43Z'
        deliveryOptions:
          - deliveryFormat: QRCODE
            deliveryValue: ''
    UnitType:
      type: string
      enum:
        - ADULT
        - YOUTH
        - CHILD
        - INFANT
        - FAMILY
        - SENIOR
        - STUDENT
        - MILITARY
        - OTHER
      example: ADULT
